"""
Populate contacts.csv names + emails via Hunter.io Domain Search API.

For each company domain, queries /v2/domain-search and matches returned
contacts to the three target roles (CEO/Founder, GTM Lead, People/Talent)
by scanning the 'position' field for role keywords.

Writes:
  pipeline/domain_search_cache.csv   — raw Hunter results (all contacts found)
  pipeline/contacts.csv              — name + work_email filled where found

Usage:
  python scripts/domain_search.py [--dry-run] [--force]

Requires:
  HUNTER_API_KEY in .env or environment
  pipeline/company_domains.csv with primary_domain filled
  pipeline/contacts.csv (generated by build_contacts_outreach.py)
"""
from __future__ import annotations

import argparse
import csv
import os
import sys
import time
from pathlib import Path

try:
    import requests
except ImportError:
    print("Install dependencies: pip install -r requirements.txt", file=sys.stderr)
    raise

HUNTER_DOMAIN_URL = "https://api.hunter.io/v2/domain-search"

# Keywords to classify a contact's position into a role bucket
ROLE_KEYWORDS: dict[str, list[str]] = {
    "ceo": ["founder", "ceo", "co-founder", "cofounder", "chief executive", "managing director", "president"],
    "gtm": ["growth", "marketing", "sales", "gtm", "revenue", "commercial", "business development",
            "vp product", "product lead", "demand", "partnerships", "go-to-market",
            "account executive", "account manager", "head of sales", "director of sales",
            "director of marketing", "chief of staff"],
    "people": ["people", "talent", "hr ", "human resources", "recruiting", "recruiter", "head of people"],
}


def load_env_file(path: Path) -> None:
    if not path.is_file():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        key, val = key.strip(), val.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = val


def read_domains(root: Path) -> dict[str, str]:
    path = root / "pipeline" / "company_domains.csv"
    out: dict[str, str] = {}
    with path.open(newline="", encoding="utf-8-sig") as f:
        for row in csv.DictReader(f):
            cid = (row.get("company_id") or "").strip()
            dom = (row.get("primary_domain") or "").strip().lower()
            if cid and dom:
                out[cid] = dom
    return out


def classify_position(position: str) -> str | None:
    """Return 'ceo', 'gtm', or 'people' based on position text, else None."""
    pos_lower = position.lower()
    for bucket, keywords in ROLE_KEYWORDS.items():
        for kw in keywords:
            if kw in pos_lower:
                return bucket
    return None


def hunter_domain_search(api_key: str, domain: str) -> list[dict]:
    """Return list of contact dicts from Hunter domain search."""
    params = {"domain": domain, "api_key": api_key, "limit": 10}
    r = requests.get(HUNTER_DOMAIN_URL, params=params, timeout=30)
    if r.status_code == 429:
        print(f"  [rate-limited] {domain}", file=sys.stderr)
        return []
    if r.status_code != 200:
        try:
            err_body = r.json()
        except Exception:
            err_body = r.text[:200]
        print(f"  [http {r.status_code}] {domain}: {err_body}", file=sys.stderr)
        return []
    data = r.json().get("data") or {}
    emails = data.get("emails") or []
    return list(emails)


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    load_env_file(root / ".env")

    p = argparse.ArgumentParser(description="Hunter.io domain search -> populate contacts.csv")
    p.add_argument("--dry-run", action="store_true", help="Print matches without writing")
    p.add_argument("--force", action="store_true", help="Overwrite existing names/emails")
    p.add_argument("--sleep", type=float, default=0.5, help="Seconds between API calls")
    p.add_argument("--from-cache", action="store_true",
                   help="Re-apply keyword matching from existing domain_search_cache.csv (no API calls)")
    args = p.parse_args()

    api_key = (os.environ.get("HUNTER_API_KEY") or "").strip()
    if not api_key and not args.dry_run and not args.from_cache:
        print("Set HUNTER_API_KEY or use --dry-run.", file=sys.stderr)
        sys.exit(1)

    domains_by_company = read_domains(root)

    contacts_path = root / "pipeline" / "contacts.csv"
    if not contacts_path.is_file():
        print("Run build_contacts_outreach.py first.", file=sys.stderr)
        sys.exit(1)

    with contacts_path.open(newline="", encoding="utf-8-sig") as f:
        contact_rows = list(csv.DictReader(f))
        fieldnames = list(contact_rows[0].keys()) if contact_rows else []

    # Build lookup: (company_id, role_bucket) -> list of contact row indices
    def role_bucket(role: str) -> str:
        r = role.lower()
        if any(k in r for k in ["founder", "ceo", "co-founder"]):
            return "ceo"
        if any(k in r for k in ["people", "talent", "hr"]):
            return "people"
        return "gtm"

    # Group contact rows by company_id -> {bucket: row_index}
    company_contacts: dict[str, dict[str, int]] = {}
    for idx, row in enumerate(contact_rows):
        cid = str(row.get("company_id", "")).strip()
        bucket = role_bucket(row.get("role", ""))
        company_contacts.setdefault(cid, {})[bucket] = idx

    # Cache file for raw results
    cache_path = root / "pipeline" / "domain_search_cache.csv"
    cache_rows: list[dict] = []

    # Collect unique company IDs that have a domain
    seen_companies = sorted({str(row.get("company_id", "")).strip() for row in contact_rows
                              if str(row.get("company_id", "")).strip() in domains_by_company},
                             key=lambda x: int(x))

    # Build contact list from cache or from live API
    def _cache_contacts_for(cid: str) -> list[dict]:
        """Return Hunter-format contact dicts from the local cache."""
        if not cache_path.is_file():
            return []
        out: list[dict] = []
        with cache_path.open(newline="", encoding="utf-8-sig") as f:
            for row in csv.DictReader(f):
                if str(row.get("company_id", "")).strip() == cid:
                    out.append({
                        "value":      row.get("email", ""),
                        "first_name": row.get("first_name", ""),
                        "last_name":  row.get("last_name", ""),
                        "position":   row.get("position", ""),
                        "confidence": row.get("confidence", ""),
                        "linkedin":   row.get("linkedin", ""),
                    })
        return out

    updated = 0
    for cid in seen_companies:
        domain = domains_by_company[cid]
        print(f"  {'[cache]' if args.from_cache else 'Searching'} {domain} (company {cid})...")

        if args.dry_run:
            print(f"    [dry-run] would {'read cache' if args.from_cache else 'query Hunter'} for {domain}")
            continue

        if args.from_cache:
            contacts = _cache_contacts_for(cid)
        else:
            contacts = hunter_domain_search(api_key, domain)
            time.sleep(max(args.sleep, 0))

        if not contacts:
            print(f"    -> 0 contacts")
            continue

        print(f"    -> {len(contacts)} contacts")

        # Save to cache (only when doing live queries)
        if not args.from_cache:
            for c in contacts:
                cache_rows.append({
                    "company_id": cid,
                    "domain": domain,
                    "email": c.get("value", ""),
                    "first_name": c.get("first_name", ""),
                    "last_name": c.get("last_name", ""),
                    "position": c.get("position", ""),
                    "confidence": c.get("confidence", ""),
                    "linkedin": c.get("linkedin", ""),
                })

        # Match contacts to role buckets
        best: dict[str, dict] = {}  # bucket -> best contact
        for c in contacts:
            pos = (c.get("position") or "").strip()
            if not pos:
                continue
            bucket = classify_position(pos)
            if bucket is None:
                continue
            # Prefer higher confidence
            conf = int(c.get("confidence") or 0)
            if bucket not in best or conf > int(best[bucket].get("confidence") or 0):
                best[bucket] = c

        buckets_in_company = company_contacts.get(cid, {})
        for bucket, c in best.items():
            row_idx = buckets_in_company.get(bucket)
            if row_idx is None:
                continue

            row = contact_rows[row_idx]
            existing_name = (row.get("name") or "").strip()
            existing_email = (row.get("work_email") or "").strip()

            first = (c.get("first_name") or "").strip()
            last = (c.get("last_name") or "").strip()
            full_name = f"{first} {last}".strip()
            email = (c.get("value") or "").strip().lower()

            should_update_name = args.force or (not existing_name or existing_name.upper() == "TO_RESEARCH")
            should_update_email = args.force or not existing_email

            if full_name and should_update_name:
                row["name"] = full_name
                updated += 1
                print(f"    [{bucket}] {full_name} <{email}> (pos: {c.get('position','')})")
            if email and should_update_email:
                row["work_email"] = email
                row["email_status"] = "found"
                row["email_source"] = "hunter_domain_search"

    if args.dry_run:
        print("--dry-run: no files written.")
        return

    # Write updated contacts.csv
    with contacts_path.open("w", newline="", encoding="utf-8-sig") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        w.writeheader()
        w.writerows(contact_rows)

    # Write cache (only when live queries were made)
    if cache_rows:
        cache_fieldnames = ["company_id", "domain", "email", "first_name", "last_name",
                            "position", "confidence", "linkedin"]
        with cache_path.open("w", newline="", encoding="utf-8-sig") as f:
            w = csv.DictWriter(f, fieldnames=cache_fieldnames, extrasaction="ignore")
            w.writeheader()
            w.writerows(cache_rows)
        print(f"\nCache: {cache_path} ({len(cache_rows)} rows)")

    print(f"Updated {updated} name(s) in contacts.csv.")


if __name__ == "__main__":
    main()
